In [1]:
import pandas as pd

In [2]:
data = {'Nome' : ['Leandro','Millene','Rafael','Vitória'],
        'Idade' : [25,25,40,20],
        'Peso' : [60.0,70.0,72.5,56.0],
        'Altura' : [1.80,1.60,1.74,1.60]

}
dados_alunos= pd.DataFrame(data)
dados_alunos

      Nome  Idade  Peso  Altura
0  Leandro     25  60.0    1.80
1  Millene     25  70.0    1.60
2   Rafael     40  72.5    1.74
3  Vitória     20  56.0    1.60

In [3]:
#nova coluna
dados_alunos['Unidade'] = ['Carapicuíba','Caierias','Barra Funda','Bairro do Limão']
dados_alunos

      Nome  Idade  Peso  Altura          Unidade
0  Leandro     25  60.0    1.80      Carapicuíba
1  Millene     25  70.0    1.60         Caierias
2   Rafael     40  72.5    1.74      Barra Funda
3  Vitória     20  56.0    1.60  Bairro do Limão