In [ ]:
import pandas as pd   # importando a biblioteca pandas para o uso das funções.

In [ ]:
#Criação de uma lista

data = {'Nome': ['João','Maria','José'],
        'Idade': [20,18,35],
        'Cidade': ['Pinda','Paraisópolis','Itaquera']
}
# a variável 'data' conterá os valores da lista

df = pd.DataFrame(data) # chama a função DataFrame da biblioteca Pandas,para fazer a leitura dos dados da variável 'data' e atribuir para á variável 'df'
df

    Nome  Idade        Cidade
0   João     20         Pinda
1  Maria     18  Paraisópolis
2   José     35      Itaquera

In [ ]:
df.head() # mostra os 5 primeiros itens do data frame (nesse caso o nosso está com poucos dados)

    Nome  Idade        Cidade
0   João     20         Pinda
1  Maria     18  Paraisópolis
2   José     35      Itaquera

In [ ]:
df.tail() # mostra os cinco últimos itens do data frame

    Nome  Idade        Cidade
0   João     20         Pinda
1  Maria     18  Paraisópolis
2   José     35      Itaquera

In [ ]:
df.info() # o .info informa característica do dataframe, Nome da coluna, quantos dados presentes, se há valores nulos, tipo de dados, e uso de memória em bytes.

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nome    3 non-null      str
 1   Idade   3 non-null      int64
 2   Cidade  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [7]:
df.describe() # informações relacionada a estatísticas

           Idade
count   3.000000
mean   24.333333
std     9.291573
min    18.000000
25%    19.000000
50%    20.000000
75%    27.500000
max    35.000000

In [ ]:
# Adicionando nova coluna com novos dados

df ={'Nomes': ['Bernardo','Fátima','Henrique'],
     'Idade':[20,40,60]
     }

df = pd.DataFrame(df)
df ['Notas'] = [7,8,10] # adiciona uma nova coluna chamada "Notas" com os valores 7,8,10
df

      Nomes  Idade  Notas
0  Bernardo     20      7
1    Fátima     40      8
2  Henrique     60     10

In [ ]:
#APAGANDO COLUNA

#criando novo dataframe a partir do anterior, mas com a remação de uma coluna específicas

df_alunos_sem_idade = df.drop('Idade',axis=1)  # . drop --> deleta coluna | axis=1  -- > argumento que específica que ação é para fazer em colunas e vez de apagar linhas(dado único correspondente ao nome fornecido)
print("DataFrame sem a coluna 'Idade' :")
print (df_alunos_sem_idade)

DataFrame sem a coluna 'Idade' :
      Nomes  Notas
0  Bernardo      7
1    Fátima      8
2  Henrique     10